import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Profile card component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Victor Crest 26 London 80K Followers 803K Likes 1.4K Photos</main>

      <footer>
        <div>
          Challenge by{" "}
          <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
            Frontend Mentor
          </a>
          . Coded by <a href="#">Your Name Here</a>.
        </div>
      </footer>
    </div>
  );
}
