import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="h-screen bg-images">
      <Head>
        <title>Frontend Mentor | Profile card component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="h-screen flex flex-col items-center justify-center mx-4">
          <Card />
        </div>
      </main>

      <footer className="absolute bottom-0 right-0 text-xs">
        <div>
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            rel="noreferrer"
            target="_blank"
          >
            Frontend Mentor
          </a>
          . Coded by <a href="#">Your Name Here</a>.
        </div>
      </footer>
    </div>
  );
}

function Card() {
  return (
    <div className="bg-white flex flex-col rounded-2xl shadow-sm w-full xs:w-[360px]">
      <div className="bg-card-pattern rounded-t-2xl bg-cover bg-no-repeat bg-center h-36 relative flex justify-center items-center">
        <div className="rounded-full h-[112px] w-[112px] border-4 border-white relative -bottom-1/2">
          <Image
            className="rounded-full"
            src="/image-victor.jpg"
            alt="avatar"
            width="112"
            height="112"
          />
        </div>
      </div>

      <div className="text-center h-32 flex items-end justify-center leading-10">
        <div>
          <h1 className="inline text-lg tracking-wide font-bold">
            Victor Crest
          </h1>
          <span className="text-dark-gray ml-3 text-lg">26</span>
          <p className="text-dark-gray text-sm">London</p>
        </div>
      </div>

      <HorizontalLine className="mt-6" />

      <div className="flex justify-around px-4 h-24">
        <CardInfo value="80K" label="Followers" />
        <CardInfo value="803K" label="Likes" />
        <CardInfo value="1.4K" label="Photos" />
      </div>
    </div>
  );
}

function HorizontalLine({ className }) {
  return <div className={`h-px bg-[#eee] w-full ${className}`}></div>;
}

function CardInfo({ label, value }) {
  return (
    <div className="flex flex-col justify-center items-center">
      <strong className="text-lg tracking-wide">{value}</strong>
      <span className="text-dark-gray text-xs tracking-wider">{label}</span>
    </div>
  );
}
